# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/" # Location of package manifests
    schedule:
      interval: "cron"
      cronjob: "0 12 * * 6" #Saturday at 12:00 UTC
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
    groups:
      minor-and-patch:
        update-types:
          - "patch"
          - "minor"
        patterns:
          - "*"
      major:
        update-types:
          - "major"
        patterns:
          - "*"
